### ISSUE TITLE
Cannot run jar locally

### ISSUE THREAD

**Issue by gabadia** [cetic/tsimulus-ms#14]
When trying to run the microservice locally as suggested: 

java -jar tsimulus-ws.jar -h 0.0.0.0 -p 8001

we get the following exception:

c:\Java\TSimulus-ms>java -jar tsimulus-ws-1.5.jar -h localhost -p 8001
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'akka.version'
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:152)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
        at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:246)
        at akka.actor.ActorSystem$Settings.<init>(ActorSystem.scala:315)
        at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:683)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:245)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:288)
        at akka.actor.ActorSystem$.apply(ActorSystem.scala:233)
        at be.cetic.tsimulus.ws.GeneratorWebServer$.main(GeneratorWebServer.scala:67)
        at be.cetic.tsimulus.ws.GeneratorWebServer.main(GeneratorWebServer.scala)

**Comment by mgoeminne** [comment]
@terence-bigtt , it seems to be due to a missing akka.version in a configuration file that was not required in the previous version. 

Have you forgot to add the application.conf file ?

BTW, in an attempt to make thinks clearer, I'm renaming everything as tsimulus-ms and changing the version to 1.6.

**Comment by alexnuttinck** [comment]
One year later... corrected in v1.6.

https://github.com/cetic/tsimulus-ms/releases/tag/v1.6 :-).
A new Docker image has also been pushed.

I close this issue.
